#' Identify breakpoints
#'
#' @name extractBreakpoints
#' @description Extracts the breakpoints from a fitted \code{marge} model.
#' @param model The \code{marge} model to analyze. Defaults to NULL.
#' @return A numeric vector of breakpoints.
#' @export
#' @examples
#' extractBreakpoints(model = marge_mod)

extractBreakpoints <- function(model = NULL) {
  # check inputs
  if (is.null(model)) stop("Model input is missing from extractBreakpoints().")
  if (!"glm" %in% class(model)) stop("Model must be of class glm.")
  # find changepoints -> need to parse them out of coefficient names generated by marge2()
  coef_names <- names(coef(model))
  coef_names <- gsub("B_final", "", coef_names)
  coef_names <- coef_names[-which(coef_names == "Intercept")]
  coef_names <- gsub("\\)", "", gsub("\\(", "", coef_names))
  coef_names <- gsub("[A-z]|[a-z]", "", coef_names)
  changepoints_char <- gsub("-", "", gsub("_", "", coef_names))
  changepoints <- as.numeric(changepoints_char)
  return(changepoints)
}
