# workflow derived from: https://github.com/insightsengineering/bioc-check-action
# but the above action doesn't actually work lol, it always fails, so I changed it

on:
  push:
    branches:
      - dev
      - main

name: Bioc-check

jobs:
  bioc-check:
    runs-on: macos-latest
    name: Bioc-check
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: release
          http-user-agent: release
          use-public-rspm: true
      - uses: r-lib/actions/setup-r-dependencies@v2
      - name: Install dependencies
        run: |
          install.packages("BiocManager")
          BiocManager::install("BiocCheck")
        shell: Rscript {0}
      - name: Run BiocCheck & BiocCheckGitClone
        run: |
          bc_res <- BiocCheck::BiocCheck()
          bc_gc_res <- BiocCheck::BiocCheckGitClone()
          n_errors <- length(bc_res$error) + length(bc_gc_res$error)
          Sys.setenv("BC_ERRORS_TOTAL" = n_errors)
        shell: Rscript {0}
      - name: Check BiocCheck results
        run: |
          echo "total errors: $BC_ERRORS_TOTAL"
          if [[ $BC_ERRORS_TOTAL -gt 0 ]]; then exit 1; else echo "BiocCheck passed!"; fi
        shell: bash
