# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Additional help taken from https://fromthebottomoftheheap.net/2020/04/30/rendering-your-readme-with-github-actions/

on:
  push:
    branches: dev
    paths: [README.Rmd, render-README.yaml]

name: render-README

jobs:
  render:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
      - uses: r-lib/actions/setup-r-dependencies@v2
      - uses: r-lib/actions/setup-pandoc@v2

      - name: install CRAN packages
        run: Rscript -e 'install.packages(c("rmarkdown","ggplot2", "dplyr", "purrr", "remotes", "devtools", "BiocManager", "Seurat"), dependencies = TRUE)'
      - name: install BioConductor packages
        run: Rscript -e 'BiocManager::install(c("SingleCellExperiment", "scater", "scran", "scuttle", "bluster"))'
      - name: install GitHub packages
        run: Rscript -e 'remotes::install_github("jr-leary7/scLANE")'
      - name: render README
        run: Rscript -e 'rmarkdown::render("README.Rmd", output_format = "github_document", output_file = "README.md")'
      - name: commit rendered README
        run: |
          git config --local user.name "jr-leary7"
          git config --local user.email "jrleary@live.unc.edu"
          git add README.md man/figures/README-*
          git commit -m "Recompiled README.Rmd" || echo "No changes to commit"
          git push origin || echo "No changes to commit"
